local _, MPT = ...

MPT.SeasonData = {
    [15] = {name ="TWW S3", Dungeons = {503, 505, 499, 525, 542, 378, 391, 392}},
    [16] = {name = "Midnight S1", Dungeons = {557, 558, 559, 560, 239, 402, 556, 161}},
    [17] = {name = "Midnight S2", Dungeons = {}},
    [18] = {name = "Midnight S3", Dungeons = {}},
    [19] = {name = "TLT S1", Dungeons = {}},
    [20] = {name = "TLT S2", Dungeons = {}},
    [21] = {name = "TLT S3", Dungeons = {}},
}

function MPT:GetDungeonName(cmap)
    local name = cmap and self.maptoID[cmap] and self.maptoID[cmap][2] or "Unknown"
    return self:Utf8Sub(name, 1, self.DungeonName.Shorten)
end

MPT.maptoID = { -- MapChallengeMode = JournalInstance
    -- Wrath of the Lich King
    [556] = {278, "Pit of Saron"},
    -- Cata
    [438] = {68, "Vortex Pinnacle"},
    [456] = {65, "Throne"},
    [507] = {71, "Grim Batol"},
    [541] = {67, "Stonecore"},
    -- MoP
    [2] =  {313, "Jade Serpent"},
    [56] = {302, "Stromsout"},
    [57] = {303, "Setting Sun"},
    [58] = {312, "Shadow-Pan"},
    [59] = {324, "Niuzao"},
    [60] = {321, "Mogu'shan"},
    [76] = {246, "Scholomance"},
    [77] = {311, "Scarlet Halls"},
    [78] = {316, "Monastery"},
    
    -- WoD
    [161] = {476, "Skyreach"},
    [163] = {385, "Slag Mines"},
    [164] = {547, "Auchindoun"},
    [165] = {537, "Shadowmoon"},
    [166] = {536, "Grimrail"},
    [167] = {559, "UBRS"},
    [168] = {556, "Everbloom"},
    [169] = {558, "Iron Docks"},
    
    -- Legion
    [197] = {716, "Eye of Azshara"},
    [198] = {762, "Darkheart"},
    [199] = {740, "BRH"},
    [200] = {721, "Halls of Valor"},
    [206] = {767, "Neltharion's Lair"},
    [207] = {707, "Vault"},
    [208] = {727, "Maw of Souls"},
    [209] = {726, "Arcway"},
    [210] = {800, "Court of Stars"},
    [227] = {860, "Kara: Lower"},
    [233] = {900, "Cathedral"},
    [234] = {860, "Kara: Upper"},
    [239] = {945, "Seat"},
    
    -- BfA
    [244] = {968, "Atal'Dazar"},
    [245] = {1001, "Freehold"},
    [246] = {1002, "Tol Dagor"},
    [247] = {1012, "Motherlode"},
    [248] = {1021, "Waycrest"},
    [249] = {1041, "King's Rest"},
    [250] = {1030, "Sethraliss"},
    [251] = {1022, "Underrot"},
    [252] = {1036, "Shrine"},
    [353] = {1023, "Boralus"},
    [369] = {1178, "Junkyard"},
    [370] = {1178, "Workshop"},
    
    -- Shadowlands
    [375] = {1184, "Mists"},
    [376] = {1182, "Necrotic Wake"},
    [377] = {1188, "Other Side"},
    [378] = {1185, "Halls of Atonement"},
    [379] = {1183, "Plaguefall"},
    [380] = {1189, "Sanguine"},
    [381] = {1186, "Spires"},
    [382] = {1187, "Theater"},
    [391] = {1194, "Streets"},
    [392] = {1194, "Gambit"},
    
    -- Dragonflight
    
    [399] = {1202, "Ruby Pools"},
    [400] = {1198, "Nokhud"},
    [401] = {1203, "Azure Vault"},
    [402] = {1201, "Academy"},
    [403] = {1197, "Uldaman"},
    [404] = {1199, "Neltharus"},
    [405] = {1196, "Brackenhide"},
    [406] = {1204, "Halls"},
    [463] = {1209, "DotI: Lower"},
    [464] = {1209, "DotI: Upper"},
    
    -- The War Within
    
    [499] = {1267, "Priory"},
    [500] = {1268, "The Rookery"},
    [501] = {1269, "Stonevault"},
    [502] = {1274, "City of Threads"},
    [503] = {1271, "Ara-Kara"},
    [504] = {1210, "Darkflame Cleft"},
    [505] = {1270, "Dawnbreaker"},
    [506] = {1272, "Cinderbrew Meadery"},
    [525] = {1298, "Floodgate"},
    [542] = {1303, "Eco-Dome"},

    -- Midnight

    [557] = {1299, "Windrunner Spire"},
    [558] = {1300, "Magisters' Terrace"},
    [559] = {1316, "Nexus-Point"},
    [560] = {1315, "Maisara Caverns"},

    --[[
    [0] = {1304, "Murder Row"},
    [0] = {1311, "Den of Nalorakk"},
    [0] = {1309, "Blinding Vale"},
    [0] = {1313, "Voidscar Arena"},
    ]]    
}

MPT.DefaultProfile = {
    Version = 1,
    name = "default",
    Spacing = 3,
    UpdateRate = 0.2,
    Scale = 1,
    HideTracker = true,
    CloseBags = true,
    KeySlot = true,
    FrameStrata = "HIGH",
    Background = {
        enabled = true,
        Color = {0, 0, 0, 0.5},
        WidthOffset = 0,
        HeightOffset = 0,
        xOffset = 0,
        yOffset = 0,
        BorderColor = {0, 0, 0, 1},
        BorderSize = 1,
    },
    Position = {
        xOffset = 0,
        yOffset = 250,
        Anchor = "RIGHT",
        relativeTo = "RIGHT",
    },
    KeyLevel = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        xOffset = 0,
        yOffset = -2,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    DungeonName = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        xOffset = 30,
        yOffset = -2,
        Font = "Expressway",
        FontSize = 16,
        Shorten = 15,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    AffixIcons = {
        enabled = true,
        Anchor = "CENTER",
        RelativeTo = "CENTER",
        xOffset = 0,
        yOffset = -2,
        Font = "Expressway",
        FontSize = 14,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    DeathCounter = {
        enabled = true,
        Iconenabled = true,
        IconAnchor = "RIGHT",
        IconRelativeTo = "RIGHT",
        IconxOffset = 0,
        IconyOffset = 0,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = -16,
        yOffset = -1,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    KeyInfo = {
        AnchoredTo = "MainFrame",
        Anchor = "TOPLEFT",
        RelativeTo = "TOPLEFT",
        Width = 330,
        Height = 14,
        xOffset = 0,
        yOffset = 0,
    },
    TimerBar = {
        Anchor = "TOPLEFT",
        RelativeTo = "BOTTOMLEFT",
        AnchoredTo = "KeyInfo",
        Splits = true,        
        ChestTimerDisplay = 1, -- 1 == relevant timers. 2 == all timers. 3 = no timers
        Width = 330,
        Height = 24,
        xOffset = 0,
        yOffset = 0,
        Texture = "Details Flat",
        Color = {
            {89/255, 90/255, 92/255, 1},
            {1, 112/255, 0, 1},
            {1, 1, 0, 1},
            {128/255, 1, 0, 1},
        },
        BorderSize = 1,
        BackgroundColor = {0, 0, 0, 0.5},
        BorderColor = {0, 0, 0, 1},
    },
    TimerText = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        xOffset = 2,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ComparisonTimer = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "LEFT",
        xOffset = 0,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        SuccessColor = {0, 1, 0, 1},
        EqualColor = {1, 0.8, 0, 1},
        FailColor = {1, 0, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ChestTimer1 = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = 0,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        BehindColor = {1, 0, 0, 1},
        AheadColor = {0, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ChestTimer2 = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = -65,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        BehindColor = {1, 0, 0, 1},
        AheadColor = {0, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ChestTimer3 = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = -130,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        BehindColor = {1, 0, 0, 1},
        AheadColor = {0, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    Ticks = {
        enabled = true,
        Width = 2,
        Color = {1, 1, 1, 1},
    },
    Bosses = {
        Anchor = "TOPLEFT",
        RelativeTo = "BOTTOMLEFT",
        AnchoredTo = "TimerBar",
        Width = 330,
        Height = 16,
        xOffset = 0,
        yOffset = 0,
    },
    BossName = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        MaxLength = 20,
        xOffset = 2,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        CompletionColor = {0, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    BossTimer = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = 0,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
        SuccessColor = {0, 1, 0, 1},
        EqualColor = {1, 0.8, 0, 1},
        FailColor = {1, 0, 0, 1},
    },
    BossSplit = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = -70,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
        SuccessColor = {0, 1, 0, 1},
        EqualColor = {1, 0.8, 0, 1},
        FailColor = {1, 0, 0, 1},
    },
    PercentCount = {
        enabled = true,
        Anchor = "LEFT",
        RelativeTo = "LEFT",
        xOffset = 2,
        yOffset = 0,
        remaining = false,
        pullcount = true,
        afterPull = true,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    RealCount = {
        enabled = true,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        xOffset = -1,
        yOffset = 0,
        Font = "Expressway",
        remaining = true,
        pullcount = true,
        afterPull = true,
        total = false,
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ForcesSplits = {
        enabled = true,
        Anchor = "CENTER",
        RelativeTo = "CENTER",
        xOffset = -30,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        SuccessColor = {0, 1, 0, 1},
        FailColor = {1, 0, 0, 1},
        EqualColor = {1, 1, 0, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ForcesCompletion = {
        enabled = true,
        Anchor = "CENTER",
        RelativeTo = "CENTER",
        xOffset = 30,
        yOffset = 0,
        Font = "Expressway",
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },
    ForcesBar = {
        Anchor = "TOPLEFT",
        RelativeTo = "BOTTOMLEFT",
        AnchoredTo = "Bosses",
        enabled = true,
        Width = 330,
        Height = 24,
        xOffset = 0,
        yOffset = 0,
        Texture = "Details Flat",
        PullText = true,
        Color = {
            {1, 117/255, 128/255, 1},
            {1, 130/255, 72/255, 1},
            {1, 197/255, 103/255, 1},
            {1, 249/255, 150/255, 1},
            {104/255, 205/255, 1, 1},
        },
        CompletionColor = {205/255, 1, 167/255, 1},
        BorderSize = 1,
        BackgroundColor = {0, 0, 0, 0.5},
        BorderColor = {0, 0, 0, 1},
    },
    
    PBInfo = {
        enabled = false,
        Anchor = "RIGHT",
        RelativeTo = "RIGHT",
        AnchoredTo = "ForcesBar",
        xOffset = 0,
        yOffset = -24,
        Font = "Expressway",
        Format = 1,  -- 1 == DD/MM/YY   2 == MM/DD/YY
        FontSize = 16,
        Outline = "OUTLINE",
        Color = {1, 1, 1, 1},
        ShadowColor = {0, 0, 0, 1},
        ShadowOffset = {0, 0},
    },

    CurrentPullBar = {
        enabled = true,
        Texture = "Details Flat",
        Color = {0, 1, 0, 1},
    }
}
MPT.AnchorTypes = {
    ["MainFrame"] = true,
    ["KeyInfo"] = true,
    ["TimerBar"] = true,
    ["Bosses"] = true,
    ["ForcesBar"] = true,
}